# Change these first
owner: alexhansford # Your GitHub organization or username, where this repository lives
repo: status-upptime # The name of this repository

sites:
  - name: Unraid
    url: https://unraid.thehansfords.co.uk
  - name: Plex
    url: https://plex.thehansfords.co.uk
 # - name: IPv6 website
 #   url: forwardemail.net
 #   port: 80
 #   check: "tcp-ping"
 #   ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime-test.alexhansford.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/alexhansford/upptime-test.alexhansford.com/master/static/img/all_logo.gif
  name: The Hansfords
  introTitle: "Quickly check the status of all The Hansford's services."
  introMessage: Check whether our home server is up or offline.
  # navbar:
  #  - title: Maths Circle Status
  #    href: /
  #  - title: Maths Circle
  #    href: https://mathscircle.com
  robotsText: "User-agent: * \n Disallow: /"
  theme: dark


workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/10 * * * *"  #set to once every 10 minutes to reduce build minutes.

i18n:
  footer: "[The Hansfords](https://thehansfords.co.uk)"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
